---
- name: "Configuring git | adding git user.name"
  become: yes
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.config/git"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0755"
    state: directory

- name: "Configuring git | adding git user.name"
  become: yes
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.config/git/config"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0644"
    state: touch

- name: "Configuring git | adding git user.name"
  become: yes
  ansible.builtin.lineinfile:
    path: "/home/{{ item.username }}/.config/git/config"
    line: "[user]"
    insertafter: "EOF"

- name: "Configuring git | adding git user.email"
  become: yes
  ansible.builtin.lineinfile:
    path: "/home/{{ item.username }}/.config/git/config"
    insertafter: '^\[user\]$'
    line: " email = {{ git_email }}"

- name: "Configuring git | adding git user.name"
  become: yes
  ansible.builtin.lineinfile:
    path: "/home/{{ item.username }}/.config/git/config"
    insertafter: '^\[user\]$'
    line: " name = {{ git_username }}"
    #  when: "item.git_auth|d(false)|bool == true"
- name: "Retrieving {{ item.username }}'s public key"
  become: yes
  ansible.builtin.slurp:
    src: '/home/{{ item.username }}/.ssh/{{ git_pubkey }}.pub'
  register: local_pubkey

- name: "Adding {{ item.username }}'s key to {{ git_username }}'s github account"
  community.general.github_key:
    name: "Access key for {{ item.username }}@{{ ansible_hostname }}"
    token: "{{ github_PAT }}"
    pubkey: "{{ local_pubkey['content'] | b64decode }}"


