---
- name: "Installing qemu-guest-agent"
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  become: yes

- name: "Starting qemu-guest-agent"
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    enabled: true
    state: started
  become: yes


