---
- name: "Provisioning a debian server"
  hosts: deboxes
  vars_prompt:
    - name: "overwrite_password"
      prompt: "Enter a new password and overwrite the old? t/F"

    - name: "prompt_password"
      prompt: "Enter a password for noah"
      private: yes

  vars_files:
    - group_vars/all/workstation-ssh-keys.secret

  roles:
    - role: sec/ssh
    - role: usr/create-user
      vars:
        user:
          username: noah
          password: "{{ prompt_password | password_hash('sha512') }}"
          create_ssh_key: true
          sudo: true
          state: present
          git_auth: false
          overwrite_password: overwrite_password
          
    - role: usr/sync-ssh-keys
      vars:
        target_user: noah
