---
- hosts: deboxes
  vars_files:
    - group_vars/servers/users.yml
    - group_vars/all/workstation-ssh-keys.secret

  roles:
    - role: usr/create-user
    # - role: nextcloud.admin.install_nextcloud
    # - role: usr/sync-ssh-keys
    #  vars:
    #    target_user: otto
    #- role: usr/sync-ssh-keys
    #  vars:
    #    target_user: noah
    #- role: usr/create-user
    #    - role: apps/docker
