---
- name: "Base server configuration for debvms group"
  hosts: debvms

  roles:
    - role: usr/create-ansible-user
    - role: sys/deb-base
    - role: sec/ufw
    - role: sec/ssh
    - role: sys/qemu-agent
