---
# Playbook to set up my own personal dev environment
# TODO:
# Setup & configure git - role
# Install graphics drivers - role
# Pull in nvim, tmux, and zsh configs
# Pipewire - role
# Set up de - role
# MPD - role
# Add new user ssh key into workstation ssh keys file
# WG module - last probably

- name: "Setting up personal environment for Noah"
  remote_user: otto
  hosts: archwks
  vars_prompt:
    - name: pass_change
      prompt: "Would you like to set a new password for target user? (0/1)"
      private: false
      default: 0

    - name: password
      prompt: "Enter password for target user (Enter to skip)"
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7

    - name: audio_srv
      prompt: "Install an audio server?\n 1. Pipewire\n 2. None\n* enter 1 or 2"
      private: false
      default: 2

    - name: d_env
      prompt: "Install a desktop environment?\n 1. DWM\n 2. Gnome\n 3. None\n* enter 1, 2, or 3"
      private: false
      default: 3

    - name: wg_vpn
      prompt: "Install Wireguard VPN? (0/1)"
      private: false
      default: 0


  vars:
    target_user: noah
    xdg_config_home: "/home/{{ target_user }}/.config"
    git_config_dir: "/home/{{ target_user }}/.config/git"
    nvim_repo: "neovim"
    tmux_repo: "tmux"
    zsh_repo: "zsh"

  roles:
    - usr/XDG_base_directories
    - usr/git_usr_configs

  pre_tasks:
      # Create users defined in group vars
    - name: "Creating users"
      ansible.builtin.include_role:
        name: usr/create-user-loop

    # Checking to ensure user & home dir was created successfully
    - name: "Checking if target user '{{ target_user }}' exists"
      ansible.builtin.user:
        name: "{{ target_user }}"
      check_mode: true
      register: target_user_check

    - name: "Checking if target user '{{ target_user }}' has a home directory"
      ansible.builtin.stat:
        path: "/home/{{ target_user }}"
      register: target_home_check

    - name: debug
      ansible.builtin.debug:
        var: target_user_check

    - name: "Asserting target user '{{ target_user }}' exists"
      ansible.builtin.assert:
        that: 'target_user_check.state == "present" and target_home_check.stat.exists'

    # Assigning password to created user, defined in vars prompts
    - name: "Assigning password to {{ target_user }}"
      become: yes
      ansible.builtin.user:
        name: "{{ target_user }}"
        password: "{{ password }}"
      when: pass_change == "1" 

          
  tasks:
    - name: "Installing workstation packages"
      become: yes
      community.general.pacman:
        name: "{{ workstation_pkgs }}"
        state: present
        update_cache: true

    # Enabling necessary services
    - name: "Enabling bluetooth.service"
      become: yes
      ansible.builtin.systemd_service:
        name: bluetooth.service
        enabled: true
        state: started

    - name: "Pulling ZSH configuration from {{ GIT_SSH_URL}}"
      ansible.builtin.include_role:
        name: usr/zsh_usr_configs
      vars: 
        zsh_target_dir: "{{ xdg_config_home }}/zsh"
      when: "target_user_check.shell == '/bin/zsh'"

    - name: "Pulling Tmux configuration from {{ GIT_SSH_URL }}"
      become: yes
      become_user: "{{ target_user }}"
      ansible.builtin.git:
        repo: "{{ GIT_SSH_URL }}/{{ tmux_repo }}.git"
        dest: "{{ xdg_config_home }}/tmux"
        update: true
 
    - name: "Pulling Neovim configuration from {{ GIT_SSH_URL }}"
      become: yes
      become_user: "{{ target_user }}"
      ansible.builtin.git:
        repo: "{{ GIT_SSH_URL }}/{{ nvim_repo }}.git"
        dest: "{{ xdg_config_home }}/neovim"
        update: true

    

    
        


    

    





      
  
    
      


