---
# This needs to:
# Create my user
# Install packages I like
# Do git configuration
# Copy over dotfiles for tmux, nvim, and zsh
# Copy Firefox profile/config
# Set up DWM and Suckless utilities

- name: "Setting up personal environment for Noah"
  remote_user: otto
  hosts: workstations

  vars:
    localuser:
      - username: noah
      - uid: 1011
      - shell: zsh
      - create_ssh_key: true
      - copy_ssh_key: true
      - sudo: true
      - git: true
      - user_state: present

  pre_tasks:
    - name: "Creating Noah user"



  tasks:

