---
- name: "Provisioning debvms"
  hosts: debvms

  pre_tasks:
    - name: "print user"
      debug:
        var: ansible_env.USER

  roles:
    - role: usr/create-ansible-user
    - role: usr/create-user-loop



