---
- name: "Creating the 'otto' automation user"
  hosts: lxc
  ansible_user: root
  vars_files:
    - group_vars/all/workstation-ssh-keys.secret

  roles:
    - role: usr/create-ansible-user
    - role: usr/sync-ssh-keys
      vars:
        target_user: otto



