---
- name: "Post-install configuration for Debian LXC containers"
  hosts: deblxctest
  remote_user: root
  vars_files:
    - group_vars/all/workstation-ssh-keys.secret

  roles:
    - role: sys/deb-base
    - role: usr/create-ansible-user
    - role: usr/create-user-loop



