---
- name: "Verifying UFW install"
  become: yes
  ansible.builtin.apt:
    name: ufw
    state: present

- name: "Setting UFW defaults: allow outgoing"
  become: yes
  community.general.ufw:
    direction: outgoing
    default: allow
  notify: "Enable UFW"

- name: "Allowing incoming ssh connections"
  become: yes
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
  notify: "Enable UFW"

- name: "Setting UFW defaults | deny incoming"
  become: yes
  community.general.ufw:
    direction: incoming
    default: deny

  

    

