---
- name: "Deploying UniFI Server | Installing prerequisite patches"
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - apt-transport-https
    update_cache: yes
    state: present
    become: yes

- name: "Deploying unifi server | testing"
  block:
    - name: "unifirepo | no apt key"
      ansible.builtin.get_url:
        url: "https://dl.ui.com/unifi/unifi-repo.gpg"
        dest: "/etc/apt/trusted.gpg.d/unifi-repo.gpg"

    - name: "unifirepo | apt source"
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti"
        filename: "/etc/apt/sources.list.d/100-ubnt-unifi.list"
        state: present

- name: "Deploying UniFi server | Installing UniFi server"
  ansible.builtin.apt:
    name: unifi
    update_cache: yes
    state: present
    become: yes


      

