---
- name: "Installing MongoDB | Adding source list"
  block:
    - name: "Removing existing GPG key | ensuring correct key is used"
      ansible.builtin.file:
        path: "/usr/share/keyrings/mongodb-server-{{ MongoDB_version }}.gpg"
        state: absent
      become: yes

    - name: "Adding GPG key"
      ansible.builtin.get_url:
        url: "https://www.mongodb.org/static/pgp/server-{{ MongoDB_version }}.asc"
        dest: "/usr/share/keyrings/mongodb-server-{{ MongoDB_version }}.asc"
        mode: 0644
      become: yes

    - name: "Adding MongoDB repository"
      ansible.builtin.apt_repository:
        repo: 'deb [ signed-by=/usr/share/keyrings/mongodb-server-{{ MongoDB_version }}.asc ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/{{ MongoDB_version }} main'
        filename: "mongodb-org-{{ MongoDB_version }}"
        update_cache: yes
        state: present
      become: yes

- name: "Installing MongoDB | Install MongoDB package"
  ansible.builtin.apt:
    name: mongodb-org
    state: present
  become: yes



   
