---
- name: "Verifying .ssh directory exists for {{ target_user }}"
  become: yes
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: "Verifying authorized_key file exists for {{ target_user }}"
  become: yes
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.ssh/authorized_keys"
    state: touch
    mode: '0600'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: "Importing SSH keys from the workstations group to {{ target_user }}"
  become: yes
  ansible.builtin.lineinfile:
    path: "/home/{{ target_user }}/.ssh/authorized_keys"
    create: yes
    line: "{{ item }}"
    state: present
  loop: "{{ workstation_ssh_keys }}"

  
