---
- name: 'Creating the automation group'
  become: yes
  ansible.builtin.group:
    name: automation
    gid: "{{ automation_gid }}"
    state: present


- name: 'Verifying sudo install'
  become: yes
  ansible.builtin.package:
    name: sudo
    state: present

- name: 'Adding the automation group to the sudoers file'
  become: yes
  ansible.builtin.copy:
    src: files/11-automation.txt
    dest: /etc/sudoers.d/11-automation
    validate: /usr/sbin/visudo -cf %s

- name: "Creating Otto Adding Otto to the automation group and locking the password"
  become: yes
  ansible.builtin.user:
    name: otto
    uid: "{{ automation_uuid }}"
    comment: 'Otto the "otto-mated" user ;)'
    groups: automation
    state: present
    password: '!'

- name: "Setting workstation authorized keys for Otto"
  become: yes
  ansible.posix.authorized_key:
    user: otto
    state: present
    key: "{{ item }}"
  loop: "{{ workstation_ssh_keys }}"
