---
- name: Verifying sshd configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Include"
    state: absent
  check_mode: yes
  changed_when: false
  register: dir

- name: "Creating ansible ssh config file"
  become: yes
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/10-ansible-ssh-configs.conf
    owner: "root"
    group: "root"
    mode: '644'
    state: touch

- name: Enabling public key authentication for SSH
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config.d/10-ansible-ssh-configs.conf
    line: "AuthenticationMethods publickey"
    insertafter: "EOF"
    state: present
  when: dir.found
  notify: Restart SSH daemon

- name: Disabling password authentication for SSH
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config.d/10-ansible-ssh-configs.conf
    line: "PasswordAuthentication no"
    insertafter: "EOF"
    state: present
    create: true
  when: dir.found
  notify: Restart SSH daemon

- name: Disabling root login for SSH
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config.d/10-ansible-ssh-configs.conf
    line: "PermitRootLogin no"
    insertafter: "EOF"
    state: present
    create: true
  when: dir.found
  notify: Restart SSH daemon

- name: Disable all SSH forwarding
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config.d/10-ansible-ssh-configs.conf
    line: "DisableForwarding yes"
    insertafter: "EOF"
    state: present
    create: true
  when: dir.found
  notify: Restart SSH daemon
    
- name: Ignore rhosts
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config.d/10-ansible-ssh-configs.conf
    line: "IgnoreRhosts yes"
    insertafter: "EOF"
    state: present
    create: true
  when: dir.found
  notify: Restart SSH daemon

