#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#qtile start
#/home/noah/bin/statusbar.sh &
polkit-gnome &
#feh --bg-scale /home/noah/Pictures/Wallpapers/.current/* &
#/home/noah/bin/statusbar.sh &
#slstatus &
dwmblocks &
#/home/noah/.config/dwmblocks/startup.sh
mpd &
clipmenud &
#redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print
#$3,$5}' | tr -d ',}') &
while true; do
    /usr/local/bin/dwm 2> /dev/null
done

exec startx
