# Tasks to install  & configure "essential" packages
# I.e. packages I'd want on any arch linux installation

- name: Installing essential packages
  become: yes
  community.general.pacman:
    name: "{{ packages_essential }}"
    state: latest

# Configuring makepkg
- name: Setting MAKEFLAGS in /etc/makepkg.conf
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/makepkg.conf
    regexp: '^#MAKEFLAGS="-j2"'
    line: 'MAKEFLAGS="-j{{ansible_processor_vcpus}}"'

# Linking Dash to /bin/sh - Dash installed in "essential packages" module
- name: "Relinking /bin/sh to Dash"
  ansible.builtin.file:
    src: /bin/dash
    dest: /usr/bin/sh
    state: link
    force: yes

- name: "Adding Dash re-link pacman hook"
  ansible.builtin.copy:
    src: files/dash.hook
    dest: /etc/pacman.d/hooks/dash.hook

# This allows the automation user to run pacman without password
# For use with ansible AUR module - see that project for more info
#- name: "Allow {{ ANSIBLE_AUTOMATION_USER }} to run 'sudo pacman' without a password"
#  become: yes
#  ansible.builtin.lineinfile:
#    path: /etc/sudoers.d/11-install-aur_builder
#    line: '{{ ANSIBLE_AUTOMATION_USER }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
#    create: yes
#    mode: 0644
#    validate: 'visudo -cf %s'


- name: Installing "{{ helper }}" aur helper
  kewlfft.aur.aur:
    name: "{{ helper }}"
    use: makepkg
    state: present
  become: yes
  become_user: '{{ ANSIBLE_AUTOMATION_USER }}'
  when: "helper != 0"


