---
- ansible.builtin.assert: { that: "ansible_os_family == 'Archlinux'" }

- name: '----------> Loading Microcode'
  ansible.builtin.include_tasks:
    file: load-microcode.yml

- name: '----------> Configuring Pacman'
  ansible.builtin.include_tasks:
    file: pacman.yml

- name: '----------> Installing essential packages and configure AUR'
  ansible.builtin.include_tasks:
    file: install-essential-packages.yml

- name: 'Locking ansible automation user'
  ansible.builtin.user:
    name: otto
    password_lock: true



