---
- name: Installing pacman management packages
  become: yes
  community.general.pacman:
    name: 
      - reflector
      - pacman-contrib
    state: latest

- name: Create backup copy of mirrorlist
  become: yes
  ansible.builtin.copy:
    src: /etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist.bak
    remote_src: true
    owner: root
    group: root
    mode: "644"
    force: no

- name: Configuring reflector for "{{ region }}"
  become: yes
  ansible.builtin.lineinfile: 
    dest: /etc/xdg/reflector/reflector.conf
    regexp: "^# --country France,Germany"
    line: "--country '{{ region }}'"
  notify: Start reflector

- name: Create backup copy of pacman.conf
  become: yes
  ansible.builtin.copy:
    src: /etc/pacman.conf
    dest: /etc/pacman.conf.bak
    remote_src: true
    owner: root
    group: root
    mode: "644"
    force: no

- name: "Enabling multilib"
  become: yes
  ansible.builtin.lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
  loop:
    - line: "[multilib]"
      regexp: "^\\[multilib\\]"
      insertafter: "^#\\[multilib\\]"
    - line: "Include = /etc/pacman.d/mirrorlist"
      insertafter: "^\\[multilib\\]"
      regexp: "Include = /etc/pacman.d/mirrorlist"
  notify: Update_pacman

- name: "Enabling paccache package cache cleaning script"
  become: yes
  ansible.builtin.systemd_service:
    name: paccache.timer
    state: started
    enabled: true
  notify: Update_pacman

- name: Enabling Parallel Downloads
  become: yes
  ansible.builtin.lineinfile:
    dest: "/etc/pacman.conf"
    regexp: "^#ParallelDownloads = 5"
    line: "ParallelDownloads = {{ pacman_parallel_dls }}"
  when: 'pacman_parallel_dls > 0'
  notify: Update_pacman

- name: "Creating /etc/pacman.d/hooks directory"
  become: yes
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: '0755'

- meta: flush_handlers




