# Tasks to install essential packages and configure AUR helper w/ makepkg

- name: Installing essential packages
  become: yes
  community.general.pacman:
    name: "{{ packages_essential }}"
    state: latest

# I confugre makepkg here because I need to install it in base-devel, which I do in "install essential pkgs"
- name: Setting MAKEFLAGS in /etc/makepkg.conf
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/makepkg.conf
    regexp: '^#MAKEFLAGS="-j2"'
    line: 'MAKEFLAGS="-j{{ansible_processor_vcpus}}"'

# This allows the automation user to run pacman without password
# For use with ansible AUR module - see that project for more info
- name: "Allow {{ ansible_automation_user }} to run 'sudo pacman' without a password"
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: '{{ ansible_automation_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'


- name: Installing "{{ helper }}" aur helper
  aur:
    name: "{{ helper }}"
    use: makepkg
    state: present
  become: yes
  become_user: '{{ ansible_automation_user }}'
  when: "helper != 0"


