---
- name: Verifying boot loader
  ansible.builtin.stat:
    path: "/boot/EFI/systemd/systemd-bootx64.efi"
  register: systemdboot

- name: Installing Intel microcode
  become: yes
  community.general.pacman:
    name: intel-ucode
    state: latest
  when: '"Intel" is in {{ ansible_processor }}'

- name: Enabling early microcode in systemdboot
  ansible.builtin.lineinfile:
    dest: /boot/loader/entries/arch.conf 
    line: "initrd  /intel-ucode.img"
    insertbefore: "^initrd  /initramfs-linux.img"
  become: yes


