---
- ansible.builtin.assert: { that: "ansible_os_family == 'Archlinux'" }

- ansible.builtin.debug:
    msg: 'aau: {{ ansible_user_id }}'

- name: '----------> Loading Microcode'
  ansible.builtin.include_tasks:
    file: load-microcode.yml

- name: '----------> Configuring Pacman'
  ansible.builtin.include_tasks:
    file: pacman.yml

- name: '----------> Installing essential packages and configure AUR'
  ansible.builtin.include_tasks:
    file: install-essential-packages.yml



