---
- name: Debug
  ansible.builtin.debug:
    msg: "dist release = {{ ansible_distribution_release }}, arch = {{ ansible_architecture }}"
- name: "Installing Docker | Removing Conflicting Packages"
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-compose
      - docker-doc
      - podman.docker
    state: absent
  become: yes

- name: Set DPKG architecture
  set_fact:
    dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: "Installing Docker | Adding Apt Repository" 
  block:
    - name: "Installing Docker | Adding Apt Repository | Adding GPG Key"
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/debian/gpg" 
        dest: "/etc/apt/keyrings/docker.asc"
        mode: 0644
      become: yes

    - name: "Installing Docker | Adding Apt Repository | Adding Repo"
      ansible.builtin.apt_repository:
        repo: 'deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
        filename: "/etc/apt/sources.list.d/docker.list"
        update_cache: yes
        state: present
      become: yes

- name: "Installing Docker | Installing all Docker Packages"
  become: yes
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
     
